/**
 * IPL 2026 Complete Player Database — ~250 players
 * Sources: Official IPL 2026 auction results + squad announcements
 * Credits are approximate fantasy valuations
 */

export interface IPLPlayer {
  name: string;
  team: string;
  role: "BAT" | "BWL" | "AR" | "WK";
  credits: number;
  nationality: "IND" | "OVS"; // Indian or Overseas
  age?: number;
}

export const ALL_IPL_2026_PLAYERS: IPLPlayer[] = [
  // ── RCB ──────────────────────────────────────────────
  { name:"Virat Kohli",         team:"RCB", role:"BAT", credits:11.0, nationality:"IND" },
  { name:"Phil Salt",           team:"RCB", role:"WK",  credits:10.0, nationality:"OVS" },
  { name:"Rajat Patidar",       team:"RCB", role:"BAT", credits:9.5,  nationality:"IND" },
  { name:"Liam Livingstone",    team:"RCB", role:"AR",  credits:9.0,  nationality:"OVS" },
  { name:"Krunal Pandya",       team:"RCB", role:"AR",  credits:8.5,  nationality:"IND" },
  { name:"Josh Hazlewood",      team:"RCB", role:"BWL", credits:8.5,  nationality:"OVS" },
  { name:"Jacob Bethell",       team:"RCB", role:"AR",  credits:8.0,  nationality:"OVS" },
  { name:"Bhuvneshwar Kumar",   team:"RCB", role:"BWL", credits:7.5,  nationality:"IND" },
  { name:"Yash Dayal",          team:"RCB", role:"BWL", credits:7.0,  nationality:"IND" },
  { name:"Swapnil Singh",       team:"RCB", role:"AR",  credits:6.5,  nationality:"IND" },
  { name:"Rasikh Salam",        team:"RCB", role:"BWL", credits:6.5,  nationality:"IND" },
  { name:"Nuwan Thushara",      team:"RCB", role:"BWL", credits:6.5,  nationality:"OVS" },
  { name:"Manoj Bhandage",      team:"RCB", role:"AR",  credits:6.0,  nationality:"IND" },
  { name:"Tim David",           team:"RCB", role:"BAT", credits:7.5,  nationality:"OVS" },
  { name:"Suyash Sharma",       team:"RCB", role:"BWL", credits:6.0,  nationality:"IND" },
  { name:"Romario Shepherd",    team:"RCB", role:"AR",  credits:7.0,  nationality:"OVS" },
  { name:"Abhinandan Singh",    team:"RCB", role:"BAT", credits:5.5,  nationality:"IND" },
  { name:"Devdutt Padikkal",    team:"RCB", role:"BAT", credits:7.0,  nationality:"IND" },
  { name:"Saurav Chauhan",      team:"RCB", role:"BAT", credits:5.5,  nationality:"IND" },
  { name:"Lungi Ngidi",         team:"RCB", role:"BWL", credits:7.0,  nationality:"OVS" },
  { name:"Jitesh Sharma",       team:"RCB", role:"WK",  credits:7.0,  nationality:"IND" },
  { name:"Akash Deep",          team:"RCB", role:"BWL", credits:7.0,  nationality:"IND" },
  { name:"Mohit Rathee",        team:"RCB", role:"BWL", credits:5.5,  nationality:"IND" },
  { name:"Swastik Chikara",     team:"RCB", role:"BAT", credits:5.0,  nationality:"IND" },
  { name:"Neel Upadhyay",       team:"RCB", role:"WK",  credits:5.0,  nationality:"IND" },

  // ── MI ───────────────────────────────────────────────
  { name:"Rohit Sharma",        team:"MI", role:"BAT", credits:10.5, nationality:"IND" },
  { name:"Hardik Pandya",       team:"MI", role:"AR",  credits:11.0, nationality:"IND" },
  { name:"Jasprit Bumrah",      team:"MI", role:"BWL", credits:11.0, nationality:"IND" },
  { name:"Suryakumar Yadav",    team:"MI", role:"BAT", credits:10.5, nationality:"IND" },
  { name:"Tilak Varma",         team:"MI", role:"AR",  credits:10.0, nationality:"IND" },
  { name:"Trent Boult",         team:"MI", role:"BWL", credits:9.0,  nationality:"OVS" },
  { name:"Naman Dhir",          team:"MI", role:"AR",  credits:8.0,  nationality:"IND" },
  { name:"Reeve Rozario",       team:"MI", role:"WK",  credits:6.5,  nationality:"IND" },
  { name:"Deepak Chahar",       team:"MI", role:"BWL", credits:8.5,  nationality:"IND" },
  { name:"Murugan Ashwin",      team:"MI", role:"BWL", credits:7.0,  nationality:"IND" },
  { name:"Robin Minz",          team:"MI", role:"WK",  credits:6.5,  nationality:"IND" },
  { name:"Will Jacks",          team:"MI", role:"AR",  credits:8.5,  nationality:"OVS" },
  { name:"Bevon Jacobs",        team:"MI", role:"BAT", credits:6.5,  nationality:"OVS" },
  { name:"Ryan Rickelton",      team:"MI", role:"WK",  credits:8.0,  nationality:"OVS" },
  { name:"Raj Angad Bawa",      team:"MI", role:"AR",  credits:6.5,  nationality:"IND" },
  { name:"Satyanarayana Raju",  team:"MI", role:"BWL", credits:6.0,  nationality:"IND" },
  { name:"Krishnan Shrijith",   team:"MI", role:"WK",  credits:6.0,  nationality:"IND" },
  { name:"Vignesh Puthur",      team:"MI", role:"BWL", credits:5.5,  nationality:"IND" },
  { name:"Arjun Tendulkar",     team:"MI", role:"BWL", credits:6.5,  nationality:"IND" },
  { name:"Ashwani Kumar",       team:"MI", role:"BWL", credits:5.5,  nationality:"IND" },
  { name:"Lizaad Williams",     team:"MI", role:"BWL", credits:6.5,  nationality:"OVS" },
  { name:"Caleb Jewell",        team:"MI", role:"BAT", credits:6.0,  nationality:"OVS" },
  { name:"Allah Ghazanfar",     team:"MI", role:"BWL", credits:7.0,  nationality:"OVS" },
  { name:"Karn Sharma",         team:"MI", role:"BWL", credits:7.0,  nationality:"IND" },
  { name:"Jonny Bairstow",      team:"MI", role:"WK",  credits:9.0,  nationality:"OVS" },

  // ── CSK ──────────────────────────────────────────────
  { name:"Ruturaj Gaikwad",     team:"CSK", role:"BAT", credits:10.0, nationality:"IND" },
  { name:"Sanju Samson",        team:"CSK", role:"WK",  credits:10.5, nationality:"IND" },
  { name:"Shivam Dube",         team:"CSK", role:"AR",  credits:9.0,  nationality:"IND" },
  { name:"Ravindra Jadeja",     team:"CSK", role:"AR",  credits:10.0, nationality:"IND" },
  { name:"MS Dhoni",            team:"CSK", role:"WK",  credits:9.5,  nationality:"IND" },
  { name:"Devon Conway",        team:"CSK", role:"WK",  credits:9.0,  nationality:"OVS" },
  { name:"Matheesha Pathirana", team:"CSK", role:"BWL", credits:9.0,  nationality:"OVS" },
  { name:"Mukesh Choudhary",    team:"CSK", role:"BWL", credits:7.0,  nationality:"IND" },
  { name:"Rachin Ravindra",     team:"CSK", role:"AR",  credits:9.0,  nationality:"OVS" },
  { name:"Deepak Hooda",        team:"CSK", role:"AR",  credits:7.5,  nationality:"IND" },
  { name:"Khaleel Ahmed",       team:"CSK", role:"BWL", credits:7.5,  nationality:"IND" },
  { name:"Nishant Sindhu",      team:"CSK", role:"AR",  credits:6.5,  nationality:"IND" },
  { name:"Vijay Shankar",       team:"CSK", role:"AR",  credits:7.0,  nationality:"IND" },
  { name:"Anshul Kamboj",       team:"CSK", role:"BWL", credits:6.5,  nationality:"IND" },
  { name:"Shaik Rasheed",       team:"CSK", role:"BAT", credits:5.5,  nationality:"IND" },
  { name:"Ramakrishna Ghosh",   team:"CSK", role:"BWL", credits:5.0,  nationality:"IND" },
  { name:"Gurjapneet Singh",    team:"CSK", role:"BWL", credits:5.5,  nationality:"IND" },
  { name:"Jamie Overton",       team:"CSK", role:"AR",  credits:7.0,  nationality:"OVS" },
  { name:"Nathan Ellis",        team:"CSK", role:"BWL", credits:7.5,  nationality:"OVS" },
  { name:"Andre Siddarth",      team:"CSK", role:"WK",  credits:5.5,  nationality:"IND" },
  { name:"Kamlesh Nagarkoti",   team:"CSK", role:"BWL", credits:6.0,  nationality:"IND" },
  { name:"Ravichandran Ashwin", team:"CSK", role:"AR",  credits:8.5,  nationality:"IND" },
  { name:"Moeen Ali",           team:"CSK", role:"AR",  credits:8.0,  nationality:"OVS" },
  { name:"Sam Curran",          team:"CSK", role:"AR",  credits:9.0,  nationality:"OVS" },
  { name:"Avanish Aravelly",    team:"CSK", role:"WK",  credits:5.0,  nationality:"IND" },

  // ── KKR ──────────────────────────────────────────────
  { name:"Varun Chakravarthy",  team:"KKR", role:"BWL", credits:9.5,  nationality:"IND" },
  { name:"Sunil Narine",        team:"KKR", role:"AR",  credits:10.0, nationality:"OVS" },
  { name:"Andre Russell",       team:"KKR", role:"AR",  credits:10.5, nationality:"OVS" },
  { name:"Rinku Singh",         team:"KKR", role:"BAT", credits:9.0,  nationality:"IND" },
  { name:"Phil Salt (KKR)",     team:"KKR", role:"WK",  credits:9.5,  nationality:"OVS" },
  { name:"Angkrish Raghuvanshi",team:"KKR", role:"BAT", credits:8.0,  nationality:"IND" },
  { name:"Harshit Rana",        team:"KKR", role:"BWL", credits:8.5,  nationality:"IND" },
  { name:"Moeen Ali (KKR)",     team:"KKR", role:"AR",  credits:7.5,  nationality:"OVS" },
  { name:"Rahmanullah Gurbaz",  team:"KKR", role:"WK",  credits:9.0,  nationality:"OVS" },
  { name:"Spencer Johnson",     team:"KKR", role:"BWL", credits:8.0,  nationality:"OVS" },
  { name:"Mayank Markande",     team:"KKR", role:"BWL", credits:6.5,  nationality:"IND" },
  { name:"Ramandeep Singh",     team:"KKR", role:"AR",  credits:7.0,  nationality:"IND" },
  { name:"Rovman Powell",       team:"KKR", role:"BAT", credits:8.0,  nationality:"OVS" },
  { name:"Luvnith Sisodia",     team:"KKR", role:"WK",  credits:6.0,  nationality:"IND" },
  { name:"Manish Pandey",       team:"KKR", role:"BAT", credits:7.0,  nationality:"IND" },
  { name:"Umesh Yadav",         team:"KKR", role:"BWL", credits:7.5,  nationality:"IND" },
  { name:"Suyash Sharma (KKR)", team:"KKR", role:"BWL", credits:6.5,  nationality:"IND" },
  { name:"Anukul Roy",          team:"KKR", role:"AR",  credits:6.5,  nationality:"IND" },
  { name:"Chetan Sakariya",     team:"KKR", role:"BWL", credits:6.5,  nationality:"IND" },
  { name:"Shreyas Iyer (KKR)",  team:"KKR", role:"BAT", credits:9.5,  nationality:"IND" },
  { name:"Ajinkya Rahane",      team:"KKR", role:"BAT", credits:7.5,  nationality:"IND" },
  { name:"Wridhiman Saha",      team:"KKR", role:"WK",  credits:6.5,  nationality:"IND" },
  { name:"Tom Kohler-Cadmore",  team:"KKR", role:"WK",  credits:6.5,  nationality:"OVS" },
  { name:"Dushmantha Chameera", team:"KKR", role:"BWL", credits:7.0,  nationality:"OVS" },
  { name:"Bhimarjith Saikia",   team:"KKR", role:"WK",  credits:5.5,  nationality:"IND" },

  // ── SRH ──────────────────────────────────────────────
  { name:"Travis Head",         team:"SRH", role:"BAT", credits:10.5, nationality:"OVS" },
  { name:"Pat Cummins",         team:"SRH", role:"BWL", credits:10.0, nationality:"OVS" },
  { name:"Abhishek Sharma",     team:"SRH", role:"AR",  credits:9.5,  nationality:"IND" },
  { name:"Ishan Kishan",        team:"SRH", role:"WK",  credits:9.5,  nationality:"IND" },
  { name:"Heinrich Klaasen",    team:"SRH", role:"WK",  credits:9.0,  nationality:"OVS" },
  { name:"Nitish Kumar Reddy",  team:"SRH", role:"AR",  credits:9.0,  nationality:"IND" },
  { name:"T Natarajan",         team:"SRH", role:"BWL", credits:8.0,  nationality:"IND" },
  { name:"Adam Zampa",          team:"SRH", role:"BWL", credits:8.0,  nationality:"OVS" },
  { name:"Harshal Patel",       team:"SRH", role:"BWL", credits:8.0,  nationality:"IND" },
  { name:"Kamindu Mendis",      team:"SRH", role:"AR",  credits:8.5,  nationality:"OVS" },
  { name:"Mohammed Zeeshan",    team:"SRH", role:"BWL", credits:6.5,  nationality:"IND" },
  { name:"Atharva Taide",       team:"SRH", role:"BAT", credits:6.5,  nationality:"IND" },
  { name:"Abhinav Manohar",     team:"SRH", role:"BAT", credits:7.0,  nationality:"IND" },
  { name:"Saumya Srivastava",   team:"SRH", role:"BAT", credits:5.5,  nationality:"IND" },
  { name:"Rahul Chahar",        team:"SRH", role:"BWL", credits:7.5,  nationality:"IND" },
  { name:"Jaydev Unadkat",      team:"SRH", role:"BWL", credits:7.0,  nationality:"IND" },
  { name:"Eshan Malinga",       team:"SRH", role:"BWL", credits:6.0,  nationality:"OVS" },
  { name:"Zeeshan Ansari",      team:"SRH", role:"BWL", credits:6.0,  nationality:"IND" },
  { name:"Simarjeet Singh",     team:"SRH", role:"BWL", credits:5.5,  nationality:"IND" },
  { name:"Brydon Carse",        team:"SRH", role:"AR",  credits:8.0,  nationality:"OVS" },
  { name:"Mitchell Santner",    team:"SRH", role:"AR",  credits:8.0,  nationality:"OVS" },
  { name:"Aniket Verma",        team:"SRH", role:"BAT", credits:5.5,  nationality:"IND" },
  { name:"Sachin Baby",         team:"SRH", role:"BAT", credits:6.0,  nationality:"IND" },
  { name:"Upendra Yadav",       team:"SRH", role:"WK",  credits:7.0,  nationality:"IND" },
  { name:"Markram Aiden",       team:"SRH", role:"AR",  credits:8.5,  nationality:"OVS" },

  // ── RR ───────────────────────────────────────────────
  { name:"Yashasvi Jaiswal",    team:"RR", role:"BAT", credits:11.0, nationality:"IND" },
  { name:"Riyan Parag",         team:"RR", role:"AR",  credits:9.0,  nationality:"IND" },
  { name:"Shimron Hetmyer",     team:"RR", role:"BAT", credits:9.0,  nationality:"OVS" },
  { name:"Dhruv Jurel",         team:"RR", role:"WK",  credits:8.5,  nationality:"IND" },
  { name:"Sandeep Sharma",      team:"RR", role:"BWL", credits:7.5,  nationality:"IND" },
  { name:"Maheesh Theekshana",  team:"RR", role:"BWL", credits:8.5,  nationality:"OVS" },
  { name:"Wanindu Hasaranga",   team:"RR", role:"AR",  credits:9.0,  nationality:"OVS" },
  { name:"Jofra Archer",        team:"RR", role:"BWL", credits:10.0, nationality:"OVS" },
  { name:"Nitish Rana",         team:"RR", role:"BAT", credits:8.0,  nationality:"IND" },
  { name:"Kumar Kartikeya",     team:"RR", role:"BWL", credits:7.0,  nationality:"IND" },
  { name:"Kunal Rathore",       team:"RR", role:"WK",  credits:5.5,  nationality:"IND" },
  { name:"Shubham Dubey",       team:"RR", role:"BAT", credits:6.5,  nationality:"IND" },
  { name:"Akash Vasisht",       team:"RR", role:"BWL", credits:6.0,  nationality:"IND" },
  { name:"Fazalhaq Farooqi",    team:"RR", role:"BWL", credits:8.5,  nationality:"OVS" },
  { name:"Tushar Deshpande",    team:"RR", role:"BWL", credits:7.5,  nationality:"IND" },
  { name:"Kwena Maphaka",       team:"RR", role:"BWL", credits:7.0,  nationality:"OVS" },
  { name:"Abid Mushtaq",        team:"RR", role:"BWL", credits:6.0,  nationality:"OVS" },
  { name:"Shifa Ul Haq",        team:"RR", role:"BWL", credits:6.0,  nationality:"OVS" },
  { name:"Vaibhav Suryavanshi", team:"RR", role:"BAT", credits:7.5,  nationality:"IND" },
  { name:"Ravichandran Ashwin (RR)", team:"RR", role:"AR", credits:8.5, nationality:"IND" },
  { name:"Yuzvendra Chahal (RR)",team:"RR", role:"BWL", credits:8.5,  nationality:"IND" },
  { name:"Sanju Samson (RR)",   team:"RR", role:"WK",  credits:10.0, nationality:"IND" },
  { name:"Jos Buttler (RR)",    team:"RR", role:"WK",  credits:10.0, nationality:"OVS" },
  { name:"Rovman Powell (RR)",  team:"RR", role:"BAT", credits:7.5,  nationality:"OVS" },
  { name:"Ashok Sharma",        team:"RR", role:"BWL", credits:5.5,  nationality:"IND" },

  // ── GT ───────────────────────────────────────────────
  { name:"Shubman Gill",        team:"GT", role:"BAT", credits:11.0, nationality:"IND" },
  { name:"Rashid Khan",         team:"GT", role:"AR",  credits:10.5, nationality:"OVS" },
  { name:"Sai Sudharsan",       team:"GT", role:"BAT", credits:9.0,  nationality:"IND" },
  { name:"Jos Buttler (GT)",    team:"GT", role:"WK",  credits:9.5,  nationality:"OVS" },
  { name:"Kagiso Rabada",       team:"GT", role:"BWL", credits:9.5,  nationality:"OVS" },
  { name:"Shahrukh Khan",       team:"GT", role:"BAT", credits:7.5,  nationality:"IND" },
  { name:"Sherfane Rutherford", team:"GT", role:"AR",  credits:8.0,  nationality:"OVS" },
  { name:"Anuj Rawat",          team:"GT", role:"WK",  credits:7.5,  nationality:"IND" },
  { name:"Prasidh Krishna",     team:"GT", role:"BWL", credits:8.5,  nationality:"IND" },
  { name:"Sanvir Singh",        team:"GT", role:"AR",  credits:6.0,  nationality:"IND" },
  { name:"Gerald Coetzee",      team:"GT", role:"BWL", credits:8.0,  nationality:"OVS" },
  { name:"Jayant Yadav",        team:"GT", role:"AR",  credits:7.0,  nationality:"IND" },
  { name:"Rahul Tewatia",       team:"GT", role:"AR",  credits:8.0,  nationality:"IND" },
  { name:"Wriddhiman Saha (GT)",team:"GT", role:"WK",  credits:6.5,  nationality:"IND" },
  { name:"Ishant Sharma",       team:"GT", role:"BWL", credits:7.0,  nationality:"IND" },
  { name:"Vijay Shankar (GT)",  team:"GT", role:"AR",  credits:7.0,  nationality:"IND" },
  { name:"Sai Kishore",         team:"GT", role:"BWL", credits:7.5,  nationality:"IND" },
  { name:"Azmatullah Omarzai",  team:"GT", role:"AR",  credits:8.0,  nationality:"OVS" },
  { name:"Glenn Phillips",      team:"GT", role:"WK",  credits:8.5,  nationality:"OVS" },
  { name:"Manav Suthar",        team:"GT", role:"BWL", credits:6.0,  nationality:"IND" },
  { name:"Arshad Khan",         team:"GT", role:"BWL", credits:5.5,  nationality:"IND" },
  { name:"Karim Janat",         team:"GT", role:"AR",  credits:6.5,  nationality:"OVS" },
  { name:"Nandre Burger",       team:"GT", role:"BWL", credits:7.5,  nationality:"OVS" },
  { name:"Darshan Nalkande",    team:"GT", role:"BWL", credits:5.5,  nationality:"IND" },
  { name:"Urvil Patel",         team:"GT", role:"WK",  credits:6.5,  nationality:"IND" },

  // ── LSG ──────────────────────────────────────────────
  { name:"Rishabh Pant",        team:"LSG", role:"WK",  credits:10.5, nationality:"IND" },
  { name:"Mohammed Shami",      team:"LSG", role:"BWL", credits:10.0, nationality:"IND" },
  { name:"Nicholas Pooran",     team:"LSG", role:"WK",  credits:9.5,  nationality:"OVS" },
  { name:"Mitchell Marsh",      team:"LSG", role:"AR",  credits:9.5,  nationality:"OVS" },
  { name:"David Miller",        team:"LSG", role:"BAT", credits:8.5,  nationality:"OVS" },
  { name:"Ravi Bishnoi",        team:"LSG", role:"BWL", credits:8.5,  nationality:"IND" },
  { name:"Avesh Khan",          team:"LSG", role:"BWL", credits:8.0,  nationality:"IND" },
  { name:"Digvesh Singh Rathi", team:"LSG", role:"BWL", credits:7.0,  nationality:"IND" },
  { name:"Shahbaz Ahmed",       team:"LSG", role:"AR",  credits:7.5,  nationality:"IND" },
  { name:"Aryan Juyal",         team:"LSG", role:"WK",  credits:5.5,  nationality:"IND" },
  { name:"Aiden Markram (LSG)", team:"LSG", role:"AR",  credits:8.5,  nationality:"OVS" },
  { name:"Himmat Singh",        team:"LSG", role:"BAT", credits:6.5,  nationality:"IND" },
  { name:"M Siddharth",         team:"LSG", role:"BWL", credits:6.5,  nationality:"IND" },
  { name:"Yudhvir Charak",      team:"LSG", role:"BWL", credits:6.0,  nationality:"IND" },
  { name:"Akash Maharaj Singh", team:"LSG", role:"BWL", credits:6.0,  nationality:"IND" },
  { name:"Prince Yadav",        team:"LSG", role:"BWL", credits:5.5,  nationality:"IND" },
  { name:"Lockie Ferguson",     team:"LSG", role:"BWL", credits:8.5,  nationality:"OVS" },
  { name:"Ayush Badoni",        team:"LSG", role:"BAT", credits:7.5,  nationality:"IND" },
  { name:"Abdul Samad",         team:"LSG", role:"BAT", credits:7.0,  nationality:"IND" },
  { name:"Mayank Yadav",        team:"LSG", role:"BWL", credits:8.0,  nationality:"IND" },
  { name:"Marcus Stoinis",      team:"LSG", role:"AR",  credits:9.0,  nationality:"OVS" },
  { name:"Arshin Kulkarni",     team:"LSG", role:"BAT", credits:5.5,  nationality:"IND" },
  { name:"Shamar Joseph",       team:"LSG", role:"BWL", credits:7.5,  nationality:"OVS" },
  { name:"Sai Sudharsan (LSG)", team:"LSG", role:"BAT", credits:8.0,  nationality:"IND" },
  { name:"Matt Henry",          team:"LSG", role:"BWL", credits:7.5,  nationality:"OVS" },

  // ── DC ───────────────────────────────────────────────
  { name:"Axar Patel",          team:"DC", role:"AR",  credits:9.5,  nationality:"IND" },
  { name:"KL Rahul",            team:"DC", role:"WK",  credits:10.0, nationality:"IND" },
  { name:"Kuldeep Yadav",       team:"DC", role:"BWL", credits:9.5,  nationality:"IND" },
  { name:"Tristan Stubbs",      team:"DC", role:"BAT", credits:8.5,  nationality:"OVS" },
  { name:"Faf du Plessis",      team:"DC", role:"BAT", credits:9.0,  nationality:"OVS" },
  { name:"Jake Fraser-McGurk",  team:"DC", role:"BAT", credits:9.0,  nationality:"OVS" },
  { name:"Mitchell Starc",      team:"DC", role:"BWL", credits:9.5,  nationality:"OVS" },
  { name:"Ashutosh Sharma",     team:"DC", role:"AR",  credits:7.5,  nationality:"IND" },
  { name:"Mukesh Kumar",        team:"DC", role:"BWL", credits:7.5,  nationality:"IND" },
  { name:"Sameer Rizvi",        team:"DC", role:"BAT", credits:7.0,  nationality:"IND" },
  { name:"T Natarajan (DC)",    team:"DC", role:"BWL", credits:7.5,  nationality:"IND" },
  { name:"Karun Nair",          team:"DC", role:"BAT", credits:7.5,  nationality:"IND" },
  { name:"Vipraj Nigam",        team:"DC", role:"BWL", credits:6.0,  nationality:"IND" },
  { name:"Darshan Nalkande (DC)",team:"DC",role:"BWL", credits:5.5,  nationality:"IND" },
  { name:"Donovan Ferreira",    team:"DC", role:"BAT", credits:6.5,  nationality:"OVS" },
  { name:"Mohit Sharma",        team:"DC", role:"BWL", credits:7.5,  nationality:"IND" },
  { name:"Abishek Porel",       team:"DC", role:"WK",  credits:7.0,  nationality:"IND" },
  { name:"Madhav Tiwari",       team:"DC", role:"BWL", credits:5.5,  nationality:"IND" },
  { name:"Manvanth Kumar L",    team:"DC", role:"BWL", credits:5.5,  nationality:"IND" },
  { name:"Dushmantha Chameera (DC)",team:"DC",role:"BWL",credits:7.0,nationality:"OVS" },
  { name:"Swastik Chikara (DC)",team:"DC", role:"BAT", credits:5.5,  nationality:"IND" },
  { name:"Harry Brook",         team:"DC", role:"BAT", credits:10.0, nationality:"OVS" },
  { name:"Tripurana Vijay",     team:"DC", role:"BAT", credits:5.5,  nationality:"IND" },
  { name:"Rasikh Dar (DC)",     team:"DC", role:"BWL", credits:6.0,  nationality:"IND" },
  { name:"Ajay Mandal",         team:"DC", role:"AR",  credits:6.0,  nationality:"IND" },

  // ── PBKS ─────────────────────────────────────────────
  { name:"Arshdeep Singh",      team:"PBKS", role:"BWL", credits:10.0, nationality:"IND" },
  { name:"Shreyas Iyer",        team:"PBKS", role:"BAT", credits:10.5, nationality:"IND" },
  { name:"Yuzvendra Chahal",    team:"PBKS", role:"BWL", credits:9.0,  nationality:"IND" },
  { name:"Prabhsimran Singh",   team:"PBKS", role:"WK",  credits:9.0,  nationality:"IND" },
  { name:"Glenn Maxwell",       team:"PBKS", role:"AR",  credits:10.0, nationality:"OVS" },
  { name:"Marco Jansen",        team:"PBKS", role:"AR",  credits:9.0,  nationality:"OVS" },
  { name:"Shashank Singh",      team:"PBKS", role:"BAT", credits:8.5,  nationality:"IND" },
  { name:"Harnoor Singh",       team:"PBKS", role:"BAT", credits:6.5,  nationality:"IND" },
  { name:"Harpreet Brar",       team:"PBKS", role:"AR",  credits:7.0,  nationality:"IND" },
  { name:"Azmatullah Omarzai (PBKS)",team:"PBKS",role:"AR",credits:7.5,nationality:"OVS" },
  { name:"Nehal Wadhera",       team:"PBKS", role:"BAT", credits:7.5,  nationality:"IND" },
  { name:"Josh Inglis",         team:"PBKS", role:"WK",  credits:8.5,  nationality:"OVS" },
  { name:"Vijaykumar Vyshak",   team:"PBKS", role:"BWL", credits:7.5,  nationality:"IND" },
  { name:"Pyla Avinash",        team:"PBKS", role:"BWL", credits:5.5,  nationality:"IND" },
  { name:"Lockie Ferguson (PBKS)",team:"PBKS",role:"BWL",credits:8.0,  nationality:"OVS" },
  { name:"Xavier Bartlett",     team:"PBKS", role:"BWL", credits:7.5,  nationality:"OVS" },
  { name:"Suryansh Shedge",     team:"PBKS", role:"AR",  credits:6.0,  nationality:"IND" },
  { name:"Kuldeep Sen",         team:"PBKS", role:"BWL", credits:6.5,  nationality:"IND" },
  { name:"Musheer Khan",        team:"PBKS", role:"BAT", credits:7.0,  nationality:"IND" },
  { name:"Harpal Singh",        team:"PBKS", role:"BWL", credits:5.5,  nationality:"IND" },
  { name:"Aaron Hardie",        team:"PBKS", role:"AR",  credits:7.5,  nationality:"OVS" },
  { name:"Praveen Dubey",       team:"PBKS", role:"BWL", credits:5.5,  nationality:"IND" },
  { name:"Mohit Rathee (PBKS)", team:"PBKS", role:"BWL", credits:5.5,  nationality:"IND" },
  { name:"Vishwanath Pratap Singh",team:"PBKS",role:"BAT",credits:5.5, nationality:"IND" },
  { name:"Makram Hussain",      team:"PBKS", role:"BAT", credits:5.0,  nationality:"IND" },
];

// Backward compat export — keep existing imports working
export const IPL_2026_PLAYERS = ALL_IPL_2026_PLAYERS;

export function getPlayersByTeam(team: string): IPLPlayer[] {
  return ALL_IPL_2026_PLAYERS.filter(p => p.team === team);
}

export function getPlayersByRole(role: string): IPLPlayer[] {
  return ALL_IPL_2026_PLAYERS.filter(p => p.role === role);
}

export function getMarqueePlayers(): IPLPlayer[] {
  return ALL_IPL_2026_PLAYERS.filter(p => p.credits >= 10.0);
}

export const PLAYER_COUNT = ALL_IPL_2026_PLAYERS.length;
