// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/pred-card/Glassmorphism.tsx": () => import("../components/mockups/pred-card/Glassmorphism.tsx"),
  "./components/mockups/pred-card/ScoreCard.tsx": () => import("../components/mockups/pred-card/ScoreCard.tsx"),
  "./components/mockups/pred-card/Versus.tsx": () => import("../components/mockups/pred-card/Versus.tsx")
};
